### PR TITLE
Feat: perf optimisation, read-only mode and a bit of refactoring

### PR DESCRIPTION
**Pull request by FloChehab**
This is a rather big PR, I hope it won't scare you :smile: 

So a bit of context first: we were experiencing some big latency issue (100% CPU, etc.)  with @jb-leger with around 100 users on a whiteboard.

We analysed a bit what was going on and we found that there was **a lot** of messages being sent by the clients (every time the mouse move basically). So this PR aims at reducing the number of messages, and does some refactoring, tweaks along the way.

*The commits should give you a good idea of what has been done.*

## Main changes

* Websocket optimization: no compression (messages are relatively small and network traffic was not an issue) and volatile (to reduce the number of round trips between clients and the server). Volatile applies only when syncing the changes on one client to the others. The server will have all the changes anyway.
* Display the number of messages received / sent in the frontend to raise awareness among the users.
* Require a minimum variation in time and distance before sending mouse events (this throttling is disabled during drawing).
* Add a read-only mode (enable by default in prod) that disables all the tools and cursor events.

## Other changes

* Updated the css / html a bit to ease the read-only feature.
* Reorganized a bit the toolbar to have all edit-related buttons on the same side (and to ease the read-only feature).
* Fixed the 45° line drawing (for some reason I had issues with that after my refactoring -- this time it's math proof)

## Refactoring related (#38 )

* Moved shortcut function to a separate module (helps with the read-only feature),
* Read-only is handled in a separate module / service
* Created a Point class to store all points (x, y) related information.

## Notes

* I can't think of other performance optimizations on the backend side (other than on the infrastructure side -- #47 ). What is done here basically gives more time for the server to "rest" or to catchup with the delay.

* This PR should provide a good first step for #28

### CODE REVIEW

**Comment by cracker0dks** [comment]
nice job! I like the changes very much. I think it would be nice to have the following changes before merge to master:
1. The send and received count msg should be opt in (maybe a GET parameter?)
2. I think POINTER_EVENT_THRESHOLD_MIN_DIST_DELTA, POINTER_EVENT_THRESHOLD_MIN_TIME_DELTA and "update the cursor position while drawing" should be stay the way it was for small groups. We could have 2 presets: one for boards with 10 or less people (deactivated) and switch it on for 10+?
I don't want to add this right away, maybe you have other plans/ideas?

Thanks for your help and PR :)
greetings

**Comment by FloChehab** [comment]
Thanks for the feedback :)

I think you are right regarding the opt-in behaviour. On the other hand, I am not sure that get parameters would fit the need.

What I suggest for your three notes:
1. Add an 'info' button that hide / show the 'debug' info (msg count for now). Make it not selected by default for now.
2. I think that's a good UX suggestion ; I'll be glad to implement it in another PR (to reduce the hassle of maintaining this forked-branch). We could reduce the threshold for now / this PR, to smooth the user experience.
3. I think read-only (by default on loading the whiteboard) should be opt-in in the long run. Real read-only whiteboard sharing (#28) will need further changes especially in the backend ; I can make a PR for it after this one too :)

At the end, I think that all these opt-in / opt-out, threshold settings, should be made customizable with a simple config file. But I think it's out of the scope of this PR which has already quite a lot of changes.

**Comment by cracker0dks** [comment]
ok, Ive merged and change some vars so that the draw and mouse behaves like bevor. Would be nice to have that configurable.
I had to remove "volatile" from socket emit. I even had problems on localhost (many lines just didn't appear on the other clients).
greetings

**Comment by FloChehab** [comment]
Thank you for the prompt reply / merge :)
Got it for volatile ; weird we didn't see issues before.

I'll work on the configuration soon :)

**Pull request merged**
