### PR TITLE
WIP: Adapt tools for endless board

### PR DESCRIPTION
**Pull request by matbgn**
- [x] Pan tool
- [ ] Rectangle select tool
- [x] Free hand draw tool
- [x] Line tool
- [x] Rectangle tool
- [x] Circle tool
- [x] Eraser tool
- [x] Text Box tool
- [ ] Sticky note tool -> need to be fixed
- [X] Image draw to canvas

### CODE REVIEW

**Comment by matbgn** [comment]
Work in progress

**Comment by cracker0dks** [comment]
Thanks for your work (again) 👍 Sorry I have covid since  sunday... so will have a look when Im back at work again.

**Comment by matbgn** [comment]
No worry, hope you are doing well now ;-)

**Comment by cracker0dks** [comment]
looks good. I also tested the sticky notes, and they seem to work as well (could not find a fault). But we need to fix background images :)

**Comment by matbgn** [comment]
Thx for the feedback ;-) 

Where did you implement the canvas img fix? 

Are you ready for another round of peer programming to close this PR once for all :-D ? Which day?

**Comment by cracker0dks** [comment]
thought I pushed it... now you should see it in the endlessBoard branch. I'll write you an email now :)

**Pull request merged**
