### PR TITLE
Custom Html Title

### PR DESCRIPTION
**Pull request by jaqcode**
The User tna76874 requested this feature in the  issue https://github.com/cracker0dks/whiteboard/issues/27

### CODE REVIEW

**Comment by cracker0dks** [comment]
ty, I tought it was about the id :)

**Comment by semencha** [comment]
Hello!

Earlier, I thought that the name of the tab would be based on the whiteboardid parameter, but since now there is a title parameter for this, I therefore ask you to make support for the national alphabet characters for this parameter i.e. please do the conversion encodeURIComponent (title).

Sincerely, Ivan Semencha

**Comment by cracker0dks** [comment]
done with: https://github.com/cracker0dks/whiteboard/commit/707e8eacbbb51fa1429d3dc7cc38771daf0d8a17

**Comment by semencha** [comment]
Thanks

**Pull request merged**
