### PR TITLE
Feat/build chain

### PR DESCRIPTION
**Pull request by FloChehab**
Related to #38 

## Biggest changes
* Added a development and production setup (webpack, etc.).

## Other notable changes
* Moved some files
* Updated Dockerfile for lighter image size
* Reduced "bundle" size by including only some specific icons
* Removed all hard-coded libs from the repo
* Changed the color picker lib (I couldn't make the other one work with the new setup)
* Some very small tweaks due to undefined vars errors, etc.

## NB
* The github diff is a bit off for the js modules that have been moved (I did my best to move the files with git before editing them to keep track of the history).
* I haven't tested it completely yet.

### CODE REVIEW

**Comment by cracker0dks** [comment]
nice, not expacted this so fast. I like it and could not find any erros so far 👍 . The colorpicker is maybe even better for small (touch)screens. Thanks

**Comment by FloChehab** [comment]
> nice, not expected this so fast. I like it and could not find any erros so far +1 . The colorpicker is maybe even better for small (touch)screens. Thanks

Thanks for the feedback !
*If you look at the commit, you'll see that I started working on it yesterday haha*

Anyway, there are still two small things I am not fully satisfied with
* What's the best way to pin the Js dependencies,
* I think we should change a bit the folder setup:
    * Maybe having a `static` or `dist` folder with the bundling result,
    * And the `public` folder for the uploads (currently they will be removed on every build, as the `public` folder content is cleared every time) -- I'd like to prevent data losses for people upgrading the app.
    * (And play with the express server to have it work as previously.)

**Comment by cracker0dks** [comment]
mmm must admit I have not much exp with webpack so don't know the best way to solve your questions. 
However for docker: you have to mount a dir to the public folder anyway. :)

**Comment by FloChehab** [comment]
> mmm must admit I have not much exp with webpack so don't know the best way to solve your questions.
> However for docker: you have to mount a dir to the public folder anyway. :)

* I changed the output of the compiled Js / html / images to `/dist`.
* I updated the backend server script so that in continues to serve uploads from `/public/uploads` (so people can continue mounting volume on `/public` ; and there won't be data losses).
* I pinned Js dev-deps with `^`
* Updated the README to reflect the changes

At the end, if people are using docker to deploy the project, there shouldn't be breaking changes with this PR.

**Comment by cracker0dks** [comment]
Thanks again. I released version 1.5 and then merged. I think this will be the start of v2.x  🥳

**Comment by FloChehab** [comment]
Thank you @cracker0dks ; I wish I have had time to rebase but that's fine :)

**Pull request merged**
