### PR TITLE
Feature/signature pad

### PR DESCRIPTION
**Pull request by shooding**
add signature pad feature from github.com/szimek/signature_pad and rewritten in whiteboard style. Enable font awesome icon for signature signing pad.
Signature can be downloaded for later usage or draw to canvas with current imgWithSrc method.

After window resized, the signature canvas needs to be resized as well to make sure gesture and mouse click start from the same position.

`_this.signaturePad.clear();` may not be necessary each time window resized.

### CODE REVIEW

**Comment by cracker0dks** [comment]
Hey, thanks for your PR, I like the feature but it would be even better if we could draw on the maincanvas.  I have not looked into the bib yet but do you think this would be possible with reasonable effort? Or is there a reason it is seperated atm?

**Comment by shooding** [comment]
Yes, it would be best to draw on the same canvas so that the gesture can
sync to all others.
Actually i have completed that version with dynamic width which looks great
around 2.5 to 5 in width, but not satisfied enough with current curve
interpolation function.

I think the seperate signing panel is still quite useful as an option for
those user only want to upload a satisfying signature instead of sign &
undo & sign & undo in realtime.

Cracker ***@***.***> 於 2022年2月8日 週二 下午6:39 寫道：

**Comment by cracker0dks** [comment]
Do you have an unscase where you have to sign on a whiteboard? I just find the drawing style very nice :)

**Comment by cracker0dks** [comment]
ok, got it.
Because this is a "niche" featrue, I think it's best if we put it optional, so you can enable it via config (Like the WebDav feature).

**Pull request closed without merging**
